# Generated by Django 2.1.7 on 2019-04-11 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=150)),
                ('tutorial_content', models.TextField()),
                ('date_published', models.DateTimeField(default=datetime.datetime(2019, 4, 11, 18, 19, 47, 785165), verbose_name='date Published')),
            ],
        ),
    ]
