# Generated by Django 2.1.7 on 2019-04-11 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 18, 20, 8, 621357), verbose_name='date Published'),
        ),
    ]
