# Generated by Django 2.2 on 2019-04-24 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20190411_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 16, 7, 20, 73534), verbose_name='date Published'),
        ),
    ]
