# Generated by Django 2.2 on 2019-04-24 11:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_auto_20190424_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=150)),
                ('category_summary', models.CharField(max_length=150)),
                ('category_slug', models.SlugField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_slug',
            field=models.SlugField(default=1),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 16, 13, 20, 144129), verbose_name='date Published'),
        ),
        migrations.CreateModel(
            name='TutorialSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_series', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
                ('tutorial_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tutorial.TutorialCategory')),
            ],
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tutorial.TutorialSeries'),
        ),
    ]
