# Generated by Django 2.2 on 2019-04-24 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_auto_20190424_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 20, 19, 24, 3032), verbose_name='date Published'),
        ),
    ]
