# Generated by Django 2.2 on 2019-04-24 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_auto_20190424_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='tutorial_category',
            new_name='series_maincategory',
        ),
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='tutorial_series',
            new_name='series_title',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='date_published',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 20, 19, 30, 213387), verbose_name='date Published'),
        ),
    ]
