# Generated by Django 2.2.1 on 2019-05-03 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0007_auto_20190424_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialseries',
            name='series_slug',
            field=models.SlugField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 1, 51, 45, 449266), verbose_name='date Published'),
        ),
    ]
